# Generated by Django 5.2.1 on 2025-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_task_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-10 14:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
